import Providers from "@/app/(components)/layout/Providers";
import "./globals.css";

export const metadata = {
  title: "Kadhi Sacco",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body style={{ margin: 0 }}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
