import Header from "@/app/(components)/layout/Header";
import Providers from "@/app/(components)/layout/Providers";

export const metadata = {
  title: "Kadhi Sacco",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
