import Providers from "@/app/(components)/layout/Providers";
import "./globals.css";
import { createServerComponentSupabaseClient } from "@supabase/auth-helpers-nextjs";
import { headers, cookies } from "next/headers";
import Header from "./(components)/layout/Header";
import type { Notification } from "@prisma/client";
import { getNotifications } from "@/utils/fetchers";

export const metadata = {
  title: "Kadhi Sacco",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  let notifications: Notification[] = [];
  const supabase = createServerComponentSupabaseClient({
    headers,
    cookies,
  });

  const {
    data: { session },
  } = await supabase.auth.getSession();

  if (session !== null) {
    notifications = await getNotifications(session.user.id);
  }

  return (
    <html lang="en">
      <body style={{ margin: 0 }}>
        <Providers>
          {session && (
            <Header
              user={session.user.user_metadata}
              notifications={notifications}
            />
          )}

          {children}
        </Providers>
      </body>
    </html>
  );
}
