import Header from "@/app/(components)/layout/Header";
import { createServerComponentSupabaseClient } from "@supabase/auth-helpers-nextjs";
import { headers, cookies } from "next/headers";

export const metadata = {
  title: "Kadhi Sacco",
  description: "Generated by create next app",
};

export const revalidate = 0;

export default async function PageLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const supabase = createServerComponentSupabaseClient({
    headers,
    cookies,
  });

  const {
    data: { session },
  } = await supabase.auth.getSession();

  return (
    <section>
      <Header user={session!.user.user_metadata} notifications={[]} />
      {children}
    </section>
  );
}

// TODO: add notifications API
