import Header from "@/app/(components)/layout/Header";

export const metadata = {
  title: "Kadhi Sacco",
  description: "Generated by create next app",
};

export default function PageLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <section>
      <Header />
      {children}
    </section>
  );
}
